import Navbar from "./components/Navbar";
import Home from "./pages/Home";
import FeatureCard from "./components/FeatureCard";
import { FaFileAlt, FaQuestionCircle, FaLayerGroup } from "react-icons/fa";



function App() {
  return (
    <div
      className="
      min-h-screen
      bg-gradient-to-b
      from-[#0f172a]
      via-[#050816]
      to-black
      "
    >
      <Navbar />

      <div className="text-center pt-0 mb-12">
        <h1 className="text-6xl font-bold bg-gradient-to-r from-purple-500 via-pink-500 to-blue-500 bg-clip-text text-transparent">
          NoteForge AI
        </h1>

        <p className="text-gray-400 text-xl mt-4">
          Transform Any Topic Into Professional AI Notes
        </p>

        <p className="text-gray-500 mt-2">
          Generate summaries, study material, and revision notes instantly.
        </p>
      </div>




<div className="max-w-6xl mx-auto px-6 mb-16">
  <div className="grid md:grid-cols-3 gap-6">

    <FeatureCard
      icon={<FaFileAlt />}
      title="AI Notes"
      description="Generate structured notes on any topic in seconds."
    />

    <FeatureCard
      icon={<FaQuestionCircle />}
      title="AI Quiz"
      description="Test your understanding with automatically generated MCQs."
    />

    <FeatureCard
      icon={<FaLayerGroup />}
      title="AI Flashcards"
      description="Revise faster with smart flashcards generated by AI."
    />

  </div>
</div>
      <Home />
    </div>
  );
}

export default App;